In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import numpy as np
import re
import string

from sklearn.feature_extraction.text import *
import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer 
from nltk.stem.porter import PorterStemmer
from nltk.probability import FreqDist

from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from emot.emo_unicode import UNICODE_EMO, EMOTICONS

import warnings
warnings.filterwarnings('ignore')
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
smartcities100 = pd.read_csv('/Users/juliencarbonnell/Desktop/Thèse/DONNÉES/1.Twitter/smartcities100/smartcities100 tweets.csv')

In [3]:
smartcities100.head()

,tweetDate,content,twitterProfile,tweetUrl,timestamp,query,rank2020
0,Sun Jan 17 10:57:51 +0000 2021,A Delegation from @aau_ae visited @BurjeelMed...,https://twitter.com/Atatreh,https://twitter.com/Atatreh/status/13507592313...,2021-01-21T13:59:48.147Z,#AbuDhabi,42
1,Thu Jan 14 17:40:03 +0000 2021,Wizz Air #AbuDhabi is set to launch flights to...,https://twitter.com/UAE_Forsan,https://twitter.com/UAE_Forsan/status/13497732...,2021-01-21T13:59:48.147Z,#AbuDhabi,42
2,Wed Jan 20 20:25:02 +0000 2021,What a great grappling exchange by both man #A...,https://twitter.com/RdosAnjosMMA,https://twitter.com/RdosAnjosMMA/status/135198...,2021-01-21T13:59:48.147Z,#AbuDhabi,42
3,Sun Jan 17 16:55:17 +0000 2021,Totally worth the 3.5 hour drive to #AbuDhabi ...,https://twitter.com/zoomnclick,https://twitter.com/zoomnclick/status/13508491...,2021-01-21T13:59:48.147Z,#AbuDhabi,42
4,Mon Jan 18 04:44:44 +0000 2021,Good morning #AbuDhabi Ireland 🇮🇪 vs UAE 🇦🇪 fi...,https://twitter.com/ChTahirmehmood,https://twitter.com/ChTahirmehmood/status/1351...,2021-01-21T13:59:48.147Z,#AbuDhabi,42

In [4]:
# how many smartcities are there in my dataset ?
smartcities100['query'].nunique()

106

I will append my 3 case studies Taipei, Tallinn, Tel Aviv which were stored in dedicated files.

In [5]:
taipei = pd.read_csv('/Users/juliencarbonnell/Desktop/Thèse/DONNÉES/1.Twitter/Taipei/#Taipei.csv')
telaviv = pd.read_csv('/Users/juliencarbonnell/Desktop/Thèse/DONNÉES/1.Twitter/Tel Aviv/#Telaviv.csv')
tallinn = pd.read_csv('/Users/juliencarbonnell/Desktop/Thèse/DONNÉES/1.Twitter/Tallinn/#Tallinn.csv')

The ranking2020 column is missing on these 3 files. Will add it before merging the files in the same dataframe

In [6]:
taipei['rank2020'] = '8'
telaviv['rank2020'] = '50'
tallinn['rank2020'] = '59'

In [7]:
smartcities100 = pd.concat([smartcities100, taipei,telaviv,tallinn], axis=0)

In [8]:
smartcities100.shape

(110862, 7)

In [9]:
smartcities100['query'].nunique()

109

In [10]:
smartcities100['query'].value_counts()

#telaviv         17612
#Taipei          17337
#Tallinn          6295
#Brisbane         2080
#Manchester       1877
#Bilbao           1338
#Zaragoza         1290
#Montreal         1231
#Vancouver        1187
#SanFrancisco     1022
#Toronto          1000
#Amsterdam        1000
#Bangkok          1000
#Bengaluru        1000
#Bogota           1000
#Munich           1000
#Bologna          1000
#Rome             1000
#Mumbai           1000
#Oslo             1000
#Athens           1000
#Berlin           1000
#HongKong          999
#Helsinki          998
#Lagos             991
#Dublin            974
#Newcastle         973
#Barcelona         956
#Hyderabad         946
#Santiago          939
#BuenosAires       932
#Nairobi           918
#SaoPaulo          913
#Chicago           907
#Madrid            903
#Moscow            898
#CapeTown          886
#Boston            868
#Melbourne         866
#London            858
#LosAngeles        856
#Medellin          850
#AbuDhabi          832
#Abuja             828
#Rotterdam         813
#Vienna            799
#Philadelphia      786
#NewDelhi          761
#Paris             760
#Dubai             733
#Tokyo             696
#Cairo             671
#Stockholm         660
#MexicoCity        654
#Milan             600
#Lisbon            600
#Nanjing           593
#Beijing           592
#Phoenix           592
#RiodeJaneiro      590
#Denver            585
#Geneva            578
#Singapore         567
#Copenhaguen       565
#Auckland          548
#Lyon              548
#Seattle           546
#HoChiMinh         539
#Bratislava        520
#KualaLumpur       499
#Zurich            485
#Sydney            483
#Dusseldorf        481
#Tianjin           480
#Prague            473
#Budapest          465
#Seoul             455
#WashingtonDC      425
#Krakow            423
#Zhuhai            422
#StPetersburg      422
#Marseille         396
#Riyadh            358
#TheHague          349
#Shenzhen          334
#Hamburg           324
#Shanghai          314
#Ankara            313
#Chengdu           286
#Warsaw            284
#Manila            268
#Brussels          261
#Osaka             237
#Hanoi             236
#Jakarta           210
#Kiev              202
#New York          191
#Sofia             187
#Chongqing         168
#Guangzhou         167
#Hangzhou          145
#Rabat             138
#Birmingham        131
#Bucharest         126
#Hanover           117
#Makassar          112
#Gothenburg         84
#Medan              71
#Busan              64
Name: query, dtype: int64

In [11]:
smartcities100.head()

,tweetDate,content,twitterProfile,tweetUrl,timestamp,query,rank2020
0,Sun Jan 17 10:57:51 +0000 2021,A Delegation from @aau_ae visited @BurjeelMed...,https://twitter.com/Atatreh,https://twitter.com/Atatreh/status/13507592313...,2021-01-21T13:59:48.147Z,#AbuDhabi,42
1,Thu Jan 14 17:40:03 +0000 2021,Wizz Air #AbuDhabi is set to launch flights to...,https://twitter.com/UAE_Forsan,https://twitter.com/UAE_Forsan/status/13497732...,2021-01-21T13:59:48.147Z,#AbuDhabi,42
2,Wed Jan 20 20:25:02 +0000 2021,What a great grappling exchange by both man #A...,https://twitter.com/RdosAnjosMMA,https://twitter.com/RdosAnjosMMA/status/135198...,2021-01-21T13:59:48.147Z,#AbuDhabi,42
3,Sun Jan 17 16:55:17 +0000 2021,Totally worth the 3.5 hour drive to #AbuDhabi ...,https://twitter.com/zoomnclick,https://twitter.com/zoomnclick/status/13508491...,2021-01-21T13:59:48.147Z,#AbuDhabi,42
4,Mon Jan 18 04:44:44 +0000 2021,Good morning #AbuDhabi Ireland 🇮🇪 vs UAE 🇦🇪 fi...,https://twitter.com/ChTahirmehmood,https://twitter.com/ChTahirmehmood/status/1351...,2021-01-21T13:59:48.147Z,#AbuDhabi,42

# 1. extract some tweet-level features
- tweet length for each tweet
- number of words for each tweet
- number of sentences for each tweet
- average word length for each tweet

In [12]:
# how many null values in content column ?
smartcities100['content'].isna().sum()

12

In [13]:
# keep only rows when content column value is not null
smartcities100 = smartcities100[smartcities100['content'].notnull()]

In [14]:
smartcities100['content'].isna().sum()

0

In [15]:
# add a column with tweet length for each tweet
smartcities100['tweet_len'] = smartcities100['content'].apply(lambda x: len(x))

In [16]:
# add a column with number of words for each tweet
smartcities100['num_words'] = smartcities100['content'].apply(lambda x: len(x.split()))

In [17]:
# add a column with number of stopwords for each tweet
stop = stopwords.words('english')
smartcities100['stopwords'] = smartcities100['content'].apply(lambda x: len([x for x in x.split() if x in stop]))

In [18]:
#add a column with number of sentences for each tweet
smartcities100['num_sentences'] = smartcities100['content'].apply(lambda x: len(re.split( '~ ...' ,'~'.join(x.split('.')))))

In [19]:
# create function for finding average length of words per tweet
def get_avg_word_len(x):
    words = x.split()
    word_len = 0
    for word in words:
        word_len = word_len + len(word)
        
    return word_len / len(words)

# add a column with average word length for each tweet
smartcities100['avg_word_len'] = smartcities100['content'].apply(lambda x: get_avg_word_len(x))

In [20]:
# create a fuction to find the number of punctuation for each tweet
def count_punct(text):
    count = sum([1 for char in text if char in string.punctuation])
    return count

# add a column with number of punctuation for each tweet
smartcities100['punctuation'] = smartcities100['content'].apply(lambda x: count_punct(x))

In [21]:
# count number of hashtag per tweet
smartcities100['hashtags'] = smartcities100['content'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))

In [22]:
# count number of numerics per tweet
smartcities100['numerics'] = smartcities100['content'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))

In [23]:
# count number of uppercase words
smartcities100['upper'] = smartcities100['content'].apply(lambda x: len([x for x in x.split() if x.isupper()]))

In [24]:
# use vader sentiment to get % of pos, neg, neu in new columns
analyzer= SentimentIntensityAnalyzer()

smartcities100['neg'] = [analyzer.polarity_scores(v)['neg'] for v in smartcities100['content']]
smartcities100['neu'] = [analyzer.polarity_scores(v)['neu'] for v in smartcities100['content']]
smartcities100['pos'] = [analyzer.polarity_scores(v)['pos'] for v in smartcities100['content']]
smartcities100['compound'] = [analyzer.polarity_scores(v)['compound'] for v in smartcities100['content']]

In [25]:
#check the columns of my dataset
smartcities100.head()

,tweetDate,content,twitterProfile,tweetUrl,timestamp,query,rank2020,tweet_len,num_words,stopwords,num_sentences,avg_word_len,punctuation,hashtags,numerics,upper,neg,neu,pos,compound
0,Sun Jan 17 10:57:51 +0000 2021,A Delegation from @aau_ae visited @BurjeelMed...,https://twitter.com/Atatreh,https://twitter.com/Atatreh/status/13507592313...,2021-01-21T13:59:48.147Z,#AbuDhabi,42,303,38,10,2,6.973684,14,2,0,2,0.104,0.849,0.047,-0.5267
1,Thu Jan 14 17:40:03 +0000 2021,Wizz Air #AbuDhabi is set to launch flights to...,https://twitter.com/UAE_Forsan,https://twitter.com/UAE_Forsan/status/13497732...,2021-01-21T13:59:48.147Z,#AbuDhabi,42,87,12,3,1,6.333333,8,2,0,0,0.000,1.000,0.000,0.0000
2,Wed Jan 20 20:25:02 +0000 2021,What a great grappling exchange by both man #A...,https://twitter.com/RdosAnjosMMA,https://twitter.com/RdosAnjosMMA/status/135198...,2021-01-21T13:59:48.147Z,#AbuDhabi,42,53,9,3,1,5.000000,1,1,0,0,0.000,0.661,0.339,0.6249
3,Sun Jan 17 16:55:17 +0000 2021,Totally worth the 3.5 hour drive to #AbuDhabi ...,https://twitter.com/zoomnclick,https://twitter.com/zoomnclick/status/13508491...,2021-01-21T13:59:48.147Z,#AbuDhabi,42,114,18,5,1,5.388889,10,2,1,1,0.000,0.748,0.252,0.6590
4,Mon Jan 18 04:44:44 +0000 2021,Good morning #AbuDhabi Ireland 🇮🇪 vs UAE 🇦🇪 fi...,https://twitter.com/ChTahirmehmood,https://twitter.com/ChTahirmehmood/status/1351...,2021-01-21T13:59:48.147Z,#AbuDhabi,42,91,12,0,1,6.666667,7,2,0,1,0.000,0.791,0.209,0.4404

In [26]:
# Save new .csv file with lastly created columns
smartcities100.to_csv('smartcities100_.csv', index=False)

Now my dataset is complete and we can see that my 3 case studies are bigger samples from the other cities. This unbalance is not annoying since I will work on means and standard deviations values. It gives my samples more proof when compared to the whole population.

# 2. Extract city-level features 
- create a dataframe with city_id as index
- use groupby on the 'query' column 
- aggregate city-level features from the tweet-level dataframe 
- take the weight of smartcityBoWs for each city

## Create a new dataframe to store features

In [27]:
# copy the unique values from 'query' column as index in the new dataframe
index = smartcities100['query'].unique()
columns = []

# create a new DataFrame
sc100_features = pd.DataFrame(index=index, columns=columns)

In [28]:
# add rank2020 column
sc100_features = pd.concat([sc100_features, smartcities100.groupby('query').rank2020.agg(['min'])], axis=1)
sc100_features

               min
#AbuDhabi       42
#Abuja         107
#Amsterdam       9
#Ankara         57
#Athens         99
#Auckland        4
#Bangkok        71
#Barcelona      49
#Beijing        82
#Bengaluru      95
#Berlin         38
#Bilbao         24
#Birmingham     40
#Bogota         92
#Bologna        70
#Boston         36
#Bratislava     76
#Brisbane       14
#Brussels       60
#Bucharest      87
#Budapest       77
#BuenosAires    88
#Busan          46
#Cairo         106
#CapeTown      103
#Chengdu        69
#Chicago        41
#Chongqing      64
#Copenhaguen     6
#Denver         35
#Dubai          43
#Dublin         34
#Dusseldorf     13
#Geneva          7
#Gothenburg     31
#Guangzhou      68
#Hamburg        22
#Hangzhou       65
#Hanoi          84
#Hanover        33
#Helsinki        2
#HoChiMinh      83
#HongKong       32
#Hyderabad      85
#Jakarta        94
#Kiev           98
#Krakow         58
#KualaLumpur    54
#Lagos         109
#Lisbon         75
#London         15
#LosAngeles     26
#Lyon           51
#Madrid         45
#Makassar       96
#Manchester     17
#Manila        104
#Marseille      78
#Medan          97
#Medellin       72
#Melbourne      20
#MexicoCity     90
#Milan          74
#Montreal       21
#Moscow         56
#Mumbai         93
#Munich         11
#Nairobi       108
#Nanjing        66
#New York       10
#Newcastle      23
#NewDelhi       86
#Osaka          80
#Oslo            5
#Paris          61
#Philadelphia   52
#Phoenix        39
#Prague         44
#Rabat         105
#RiodeJaneiro  102
#Riyadh         53
#Rome          101
#Rotterdam      29
#SanFrancisco   27
#Santiago       91
#SaoPaulo      100
#Seattle        37
#Seoul          47
#Shanghai       81
#Shenzhen       67
#Singapore       1
#Sofia          89
#Stockholm      16
#StPetersburg   73
#Sydney         18
#TheHague       28
#Tianjin        63
#Tokyo          79
#Toronto        30
#Vancouver      19
#Vienna         25
#Warsaw         55
#WashingtonDC   12
#Zaragoza       48
#Zhuhai         62
#Zurich          3
#Taipei          8
NaN            NaN
#telaviv        50
#Tallinn        59

In [29]:
# agg num_tweets column
sc100_features = pd.concat([sc100_features, smartcities100['query'].value_counts()], axis=1)
sc100_features

               min    query
#AbuDhabi       42    832.0
#Abuja         107    828.0
#Amsterdam       9   1000.0
#Ankara         57    313.0
#Athens         99   1000.0
#Auckland        4    548.0
#Bangkok        71   1000.0
#Barcelona      49    956.0
#Beijing        82    592.0
#Bengaluru      95   1000.0
#Berlin         38   1000.0
#Bilbao         24   1338.0
#Birmingham     40    131.0
#Bogota         92   1000.0
#Bologna        70   1000.0
#Boston         36    868.0
#Bratislava     76    520.0
#Brisbane       14   2080.0
#Brussels       60    261.0
#Bucharest      87    126.0
#Budapest       77    465.0
#BuenosAires    88    932.0
#Busan          46     64.0
#Cairo         106    671.0
#CapeTown      103    886.0
#Chengdu        69    286.0
#Chicago        41    907.0
#Chongqing      64    168.0
#Copenhaguen     6    565.0
#Denver         35    585.0
#Dubai          43    733.0
#Dublin         34    974.0
#Dusseldorf     13    481.0
#Geneva          7    578.0
#Gothenburg     31     84.0
#Guangzhou      68    167.0
#Hamburg        22    324.0
#Hangzhou       65    145.0
#Hanoi          84    236.0
#Hanover        33    117.0
#Helsinki        2    998.0
#HoChiMinh      83    539.0
#HongKong       32    999.0
#Hyderabad      85    946.0
#Jakarta        94    210.0
#Kiev           98    202.0
#Krakow         58    423.0
#KualaLumpur    54    499.0
#Lagos         109    991.0
#Lisbon         75    600.0
#London         15    857.0
#LosAngeles     26    856.0
#Lyon           51    548.0
#Madrid         45    902.0
#Makassar       96    112.0
#Manchester     17   1876.0
#Manila        104    267.0
#Marseille      78    396.0
#Medan          97     71.0
#Medellin       72    850.0
#Melbourne      20    866.0
#MexicoCity     90    654.0
#Milan          74    600.0
#Montreal       21   1231.0
#Moscow         56    898.0
#Mumbai         93   1000.0
#Munich         11   1000.0
#Nairobi       108    918.0
#Nanjing        66    593.0
#New York       10    191.0
#Newcastle      23    973.0
#NewDelhi       86    761.0
#Osaka          80    237.0
#Oslo            5   1000.0
#Paris          61    760.0
#Philadelphia   52    786.0
#Phoenix        39    592.0
#Prague         44    473.0
#Rabat         105    137.0
#RiodeJaneiro  102    590.0
#Riyadh         53    358.0
#Rome          101   1000.0
#Rotterdam      29    813.0
#SanFrancisco   27   1022.0
#Santiago       91    939.0
#SaoPaulo      100    913.0
#Seattle        37    546.0
#Seoul          47    454.0
#Shanghai       81    314.0
#Shenzhen       67    334.0
#Singapore       1    567.0
#Sofia          89    187.0
#Stockholm      16    660.0
#StPetersburg   73    422.0
#Sydney         18    483.0
#TheHague       28    348.0
#Tianjin        63    480.0
#Tokyo          79    696.0
#Toronto        30   1000.0
#Vancouver      19   1186.0
#Vienna         25    799.0
#Warsaw         55    284.0
#WashingtonDC   12    425.0
#Zaragoza       48   1290.0
#Zhuhai         62    422.0
#Zurich          3    485.0
#Taipei          8  17337.0
NaN            NaN      NaN
#telaviv        50  17612.0
#Tallinn        59   6295.0

In [30]:
# agg total tweet length by city
sc100_features['total_tweet_len'] = smartcities100.groupby('query')['tweet_len'].sum()
sc100_features

               min    query  total_tweet_len
#AbuDhabi       42    832.0         161350.0
#Abuja         107    828.0         173587.0
#Amsterdam       9   1000.0         180311.0
#Ankara         57    313.0          58158.0
#Athens         99   1000.0         186752.0
#Auckland        4    548.0          91988.0
#Bangkok        71   1000.0         169520.0
#Barcelona      49    956.0         153130.0
#Beijing        82    592.0         126799.0
#Bengaluru      95   1000.0         202739.0
#Berlin         38   1000.0         166865.0
#Bilbao         24   1338.0         246561.0
#Birmingham     40    131.0          29336.0
#Bogota         92   1000.0         154957.0
#Bologna        70   1000.0         159065.0
#Boston         36    868.0         142679.0
#Bratislava     76    520.0         103829.0
#Brisbane       14   2080.0         352459.0
#Brussels       60    261.0          50759.0
#Bucharest      87    126.0          22200.0
#Budapest       77    465.0          80231.0
#BuenosAires    88    932.0         185245.0
#Busan          46     64.0           6717.0
#Cairo         106    671.0         126294.0
#CapeTown      103    886.0         174493.0
#Chengdu        69    286.0          54839.0
#Chicago        41    907.0         129698.0
#Chongqing      64    168.0          34386.0
#Copenhaguen     6    565.0          92399.0
#Denver         35    585.0         100971.0
#Dubai          43    733.0         125248.0
#Dublin         34    974.0         154054.0
#Dusseldorf     13    481.0          98852.0
#Geneva          7    578.0         119753.0
#Gothenburg     31     84.0          16655.0
#Guangzhou      68    167.0          30529.0
#Hamburg        22    324.0          59827.0
#Hangzhou       65    145.0          30747.0
#Hanoi          84    236.0          43393.0
#Hanover        33    117.0          21182.0
#Helsinki        2    998.0         168601.0
#HoChiMinh      83    539.0         119236.0
#HongKong       32    999.0         186848.0
#Hyderabad      85    946.0         195368.0
#Jakarta        94    210.0          37152.0
#Kiev           98    202.0          39080.0
#Krakow         58    423.0          74565.0
#KualaLumpur    54    499.0         106121.0
#Lagos         109    991.0         208889.0
#Lisbon         75    600.0         123655.0
#London         15    857.0         153420.0
#LosAngeles     26    856.0         164200.0
#Lyon           51    548.0          93212.0
#Madrid         45    902.0         128097.0
#Makassar       96    112.0          21287.0
#Manchester     17   1876.0         351143.0
#Manila        104    267.0          49565.0
#Marseille      78    396.0          65056.0
#Medan          97     71.0          11892.0
#Medellin       72    850.0         132224.0
#Melbourne      20    866.0         159753.0
#MexicoCity     90    654.0         125086.0
#Milan          74    600.0         101778.0
#Montreal       21   1231.0         217733.0
#Moscow         56    898.0         167425.0
#Mumbai         93   1000.0         178179.0
#Munich         11   1000.0         203658.0
#Nairobi       108    918.0         180787.0
#Nanjing        66    593.0         122333.0
#New York       10    191.0          34243.0
#Newcastle      23    973.0         193512.0
#NewDelhi       86    761.0         162550.0
#Osaka          80    237.0          45105.0
#Oslo            5   1000.0         191611.0
#Paris          61    760.0         125829.0
#Philadelphia   52    786.0         149148.0
#Phoenix        39    592.0          97044.0
#Prague         44    473.0          85922.0
#Rabat         105    137.0          26401.0
#RiodeJaneiro  102    590.0         103613.0
#Riyadh         53    358.0          70199.0
#Rome          101   1000.0         178089.0
#Rotterdam      29    813.0         127189.0
#SanFrancisco   27   1022.0         172210.0
#Santiago       91    939.0         185590.0
#SaoPaulo      100    913.0         146771.0
#Seattle        37    546.0          81287.0
#Seoul          47    454.0          80040.0
#Shanghai       81    314.0          66612.0
#Shenzhen       67    334.0          62488.0
#Singapore       1    567.0          86578.0
#Sofia          89    187.0          27422.0
#Stockholm      16    660.0         125105.0
#StPetersburg   73    422.0          74795.0
#Sydney         18    483.0          87547.0
#TheHague       28    348.0          53450.0
#Tianjin        63    480.0         102081.0
#Tokyo          79    696.0         123170.0
#Toronto        30   1000.0         158880.0
#Vancouver      19   1186.0         224408.0
#Vienna         25    799.0         155072.0
#Warsaw         55    284.0          52541.0
#WashingtonDC   12    425.0          78773.0
#Zaragoza       48   1290.0         258789.0
#Zhuhai         62    422.0          80141.0
#Zurich          3    485.0          94012.0
#Taipei          8  17337.0        2505360.0
NaN            NaN      NaN              NaN
#telaviv        50  17612.0        2468640.0
#Tallinn        59   6295.0         926238.0

In [31]:
# calculate average tweet length
sc100_features['avg_tweet_len'] = sc100_features['total_tweet_len']/sc100_features['query']

In [32]:
# agg total number of words 
sc100_features['total_num_words'] = smartcities100.groupby('query')['num_words'].sum()

In [33]:
# calculate average number of words
sc100_features['avg_num_words'] = sc100_features['total_num_words']/sc100_features['query']

In [34]:
# agg total number of stopwords 
sc100_features['total_stopwords'] = smartcities100.groupby('query')['stopwords'].sum()

In [35]:
# calculate average number of stopwords
sc100_features['avg_stopwords'] = sc100_features['total_stopwords']/sc100_features['query']

In [36]:
# agg total number of sentences 
sc100_features['total_num_sentences'] = smartcities100.groupby('query')['num_sentences'].sum()

In [37]:
# calculate average number of sentences
sc100_features['avg_num_sentences'] = sc100_features['total_num_sentences']/sc100_features['query']

In [38]:
# agg total average word length
sc100_features['total_avg_word_len'] = smartcities100.groupby('query')['avg_word_len'].sum()

In [39]:
# calculate average of average word length
sc100_features['avg_avg_word_len'] = sc100_features['total_avg_word_len']/sc100_features['query']

In [40]:
# agg total number of punctuation
sc100_features['total_punctuation'] = smartcities100.groupby('query')['punctuation'].sum()

In [41]:
# calculate average number of punctuation
sc100_features['avg_punctuation'] = sc100_features['total_punctuation']/sc100_features['query']

In [42]:
# agg total number of hashtags
sc100_features['total_hashtags'] = smartcities100.groupby('query')['hashtags'].sum()

In [43]:
# calculate average number of hashtags
sc100_features['avg_hashtags'] = sc100_features['total_hashtags']/sc100_features['query']

In [44]:
# agg total number of numerics
sc100_features['total_numerics'] = smartcities100.groupby('query')['numerics'].sum()

In [45]:
# calculate average number of numerics
sc100_features['avg_numerics'] = sc100_features['total_numerics']/sc100_features['query']

In [46]:
# agg total number of uppercase words
sc100_features['total_upper'] = smartcities100.groupby('query')['upper'].sum()

In [47]:
# calculate average number of uppercase words
sc100_features['avg_upper'] = sc100_features['total_upper']/sc100_features['query']

In [48]:
# agg total sentiment scores
sc100_features['neg'] = smartcities100.groupby('query')['neg'].sum()
sc100_features['neu'] = smartcities100.groupby('query')['neu'].sum()
sc100_features['pos'] = smartcities100.groupby('query')['pos'].sum()
sc100_features['compound'] = smartcities100.groupby('query')['compound'].sum()

In [49]:
# calculate average sentiment scores
sc100_features['avg_neg'] = sc100_features['neg']/sc100_features['query']
sc100_features['avg_neu'] = sc100_features['neu']/sc100_features['query']
sc100_features['avg_pos'] = sc100_features['pos']/sc100_features['query']
sc100_features['avg_compound'] = sc100_features['compound']/sc100_features['query']

In [50]:
sc100_features

,min,query,total_tweet_len,avg_tweet_len,total_num_words,avg_num_words,total_stopwords,avg_stopwords,total_num_sentences,avg_num_sentences,total_avg_word_len,avg_avg_word_len,total_punctuation,avg_punctuation,total_hashtags,avg_hashtags,total_numerics,avg_numerics,total_upper,avg_upper,neg,neu,pos,compound,avg_neg,avg_neu,avg_pos,avg_compound
#AbuDhabi,42,832.0,161350.0,193.930288,20802.0,25.002404,4821.0,5.794471,1194.0,1.435096,5887.253316,7.076026,11662.0,14.016827,3829.0,4.602163,232.0,0.278846,908.0,1.091346,18.248,715.630,98.123,249.5025,0.021933,0.860132,0.117936,0.299883
#Abuja,107,828.0,173587.0,209.646135,22391.0,27.042271,4621.0,5.580918,1190.0,1.437198,5858.506206,7.075491,12726.0,15.369565,4792.0,5.787440,335.0,0.404589,1046.0,1.263285,15.064,709.099,103.828,295.2426,0.018193,0.856400,0.125396,0.356573
#Amsterdam,9,1000.0,180311.0,180.311000,22627.0,22.627000,5220.0,5.220000,1520.0,1.520000,7579.218712,7.579219,14554.0,14.554000,5239.0,5.239000,153.0,0.153000,663.0,0.663000,24.567,875.009,100.439,250.7977,0.024567,0.875009,0.100439,0.250798
#Ankara,57,313.0,58158.0,185.808307,7194.0,22.984026,1244.0,3.974441,409.0,1.306709,2350.814230,7.510589,4616.0,14.747604,1760.0,5.623003,106.0,0.338658,263.0,0.840256,12.420,271.031,29.554,60.1001,0.039681,0.865914,0.094422,0.192013
#Athens,99,1000.0,186752.0,186.752000,24268.0,24.268000,5405.0,5.405000,1503.0,1.503000,7170.591520,7.170592,15201.0,15.201000,5442.0,5.442000,226.0,0.226000,865.0,0.865000,42.164,865.646,92.190,176.3919,0.042164,0.865646,0.092190,0.176392
#Auckland,4,548.0,91988.0,167.861314,12264.0,22.379562,2839.0,5.180657,778.0,1.419708,3850.556937,7.026564,7207.0,13.151460,2171.0,3.961679,207.0,0.377737,397.0,0.724453,14.853,464.284,68.852,158.3768,0.027104,0.847234,0.125642,0.289009
#Bangkok,71,1000.0,169520.0,169.520000,21284.0,21.284000,4486.0,4.486000,1550.0,1.550000,7706.239732,7.706240,13365.0,13.365000,4721.0,4.721000,274.0,0.274000,749.0,0.749000,36.695,867.573,95.729,175.7277,0.036695,0.867573,0.095729,0.175728
#Barcelona,49,956.0,153130.0,160.177824,20409.0,21.348326,5011.0,5.241632,1312.0,1.372385,6746.770100,7.057291,11263.0,11.781381,3906.0,4.085774,162.0,0.169456,664.0,0.694561,43.144,793.613,119.248,219.7659,0.045130,0.830139,0.124736,0.229881
#Beijing,82,592.0,126799.0,214.187500,17203.0,29.059122,4777.0,8.069257,970.0,1.638514,4015.975769,6.783743,8211.0,13.869932,2429.0,4.103041,185.0,0.312500,476.0,0.804054,26.444,523.655,41.901,62.1245,0.044669,0.884552,0.070779,0.104940
#Bengaluru,95,1000.0,202739.0,202.739000,25939.0,25.939000,5987.0,5.987000,1556.0,1.556000,7189.155050,7.189155,14233.0,14.233000,4029.0,4.029000,390.0,0.390000,881.0,0.881000,35.692,864.501,99.807,211.1191,0.035692,0.864501,0.099807,0.211119
#Berlin,38,1000.0,166865.0,166.865000,21171.0,21.171000,4447.0,4.447000,1539.0,1.539000,7318.530286,7.318530,13914.0,13.914000,5103.0,5.103000,163.0,0.163000,769.0,0.769000,30.785,870.707,98.508,194.5490,0.030785,0.870707,0.098508,0.194549
#Bilbao,24,1338.0,246561.0,184.275785,32198.0,24.064275,1670.0,1.248132,2099.0,1.568759,9586.112359,7.164508,17817.0,13.316143,5778.0,4.318386,346.0,0.258595,1655.0,1.236921,29.118,1262.883,45.997,50.8727,0.021762,0.943859,0.034377,0.038021
#Birmingham,40,131.0,29336.0,223.938931,4045.0,30.877863,1179.0,9.000000,225.0,1.717557,854.451016,6.522527,1956.0,14.931298,434.0,3.312977,35.0,0.267176,137.0,1.045802,4.132,110.847,16.019,42.5756,0.031542,0.846160,0.122282,0.325005
#Bogota,92,1000.0,154957.0,154.957000,19190.0,19.190000,1659.0,1.659000,1379.0,1.379000,8562.650366,8.562650,12584.0,12.584000,3845.0,3.845000,372.0,0.372000,908.0,0.908000,16.361,941.556,42.083,76.7322,0.016361,0.941556,0.042083,0.076732
#Bologna,70,1000.0,159065.0,159.065000,20315.0,20.315000,1741.0,1.741000,1366.0,1.366000,7491.525823,7.491526,13181.0,13.181000,4460.0,4.460000,196.0,0.196000,723.0,0.723000,10.812,956.737,32.443,79.5296,0.010812,0.956737,0.032443,0.079530
#Boston,36,868.0,142679.0,164.376728,19205.0,22.125576,4613.0,5.314516,1414.0,1.629032,6072.989512,6.996532,11673.0,13.448157,3066.0,3.532258,164.0,0.188940,884.0,1.018433,32.244,742.972,92.781,187.9784,0.037147,0.855959,0.106891,0.216565
#Bratislava,76,520.0,103829.0,199.671154,13353.0,25.678846,3186.0,6.126923,867.0,1.667308,3744.791206,7.201522,7540.0,14.500000,2586.0,4.973077,97.0,0.186538,411.0,0.790385,16.324,456.467,47.210,109.2366,0.031392,0.877821,0.090788,0.210070
#Brisbane,14,2080.0,352459.0,169.451442,49001.0,23.558173,12106.0,5.820192,3093.0,1.487019,13618.088491,6.547158,22944.0,11.030769,9534.0,4.583654,620.0,0.298077,1520.0,0.730769,80.080,1675.125,324.748,737.0790,0.038500,0.805349,0.156129,0.354365
#Brussels,60,261.0,50759.0,194.478927,7152.0,27.402299,2077.0,7.957854,445.0,1.704981,1682.616760,6.446808,3380.0,12.950192,844.0,3.233716,59.0,0.226054,196.0,0.750958,10.726,219.712,30.554,64.8755,0.041096,0.841808,0.117065,0.248565
#Bucharest,87,126.0,22200.0,176.190476,2726.0,21.634921,444.0,3.523810,180.0,1.428571,977.427955,7.757365,1899.0,15.071429,749.0,5.944444,42.0,0.333333,63.0,0.500000,1.133,112.986,11.880,30.2971,0.008992,0.896714,0.094286,0.240453
#Budapest,77,465.0,80231.0,172.539785,10124.0,21.772043,1760.0,3.784946,638.0,1.372043,3543.407360,7.620231,6576.0,14.141935,2199.0,4.729032,80.0,0.172043,327.0,0.703226,8.729,418.425,37.848,86.4615,0.018772,0.899839,0.081394,0.185939
#BuenosAires,88,932.0,185245.0,198.760730,23807.0,25.543991,1689.0,1.812232,1369.0,1.468884,6766.371938,7.260056,13423.0,14.402361,4649.0,4.988197,377.0,0.404506,975.0,1.046137,13.464,883.348,35.184,68.0215,0.014446,0.947798,0.037751,0.072984
#Busan,46,64.0,6717.0,104.953125,861.0,13.453125,83.0,1.296875,85.0,1.328125,501.041805,7.828778,627.0,9.796875,312.0,4.875000,1.0,0.015625,27.0,0.421875,1.211,58.117,4.671,9.5593,0.018922,0.908078,0.072984,0.149364
#Cairo,106,671.0,126294.0,188.217586,17074.0,25.445604,2511.0,3.742176,1051.0,1.566319,4541.201272,6.767811,9447.0,14.078987,3501.0,5.217586,135.0,0.201192,504.0,0.751118,13.227,610.903,46.865,108.4423,0.019712,0.910437,0.069844,0.161613
#CapeTown,103,886.0,174493.0,196.944695,22185.0,25.039503,5152.0,5.814898,1312.0,1.480813,6397.683926,7.220862,13116.0,14.803612,4458.0,5.031603,187.0,0.211061,618.0,0.697517,24.431,743.179,118.387,304.0269,0.027574,0.838802,0.133620,0.343145
#Chengdu,69,286.0,54839.0,191.744755,7396.0,25.860140,1189.0,4.157343,531.0,1.856643,2026.421509,7.085390,4210.0,14.720280,1276.0,4.461538,100.0,0.349650,231.0,0.807692,8.253,260.185,17.552,35.1091,0.028857,0.909738,0.061371,0.122759
#Chicago,41,907.0,129698.0,142.996692,16637.0,18.342889,3576.0,3.942668,1330.0,1.466373,6636.546635,7.317030,10766.0,11.869901,3346.0,3.689085,178.0,0.196251,746.0,0.822492,41.421,762.536,103.068,179.1533,0.045668,0.840723,0.113636,0.197523
#Chongqing,64,168.0,34386.0,204.678571,4564.0,27.166667,947.0,5.636905,306.0,1.821429,1241.756253,7.391406,2534.0,15.083333,803.0,4.779762,83.0,0.494048,71.0,0.422619,8.127,148.103,11.772,24.4720,0.048375,0.881565,0.070071,0.145667
#Copenhaguen,6,565.0,92399.0,163.538053,11420.0,20.212389,1485.0,2.628319,819.0,1.449558,4405.610128,7.797540,7171.0,12.692035,2284.0,4.042478,72.0,0.127434,282.0,0.499115,9.827,511.111,44.059,95.0041,0.017393,0.904621,0.077981,0.168149
#Denver,35,585.0,100971.0,172.600000,13345.0,22.811966,3137.0,5.362393,951.0,1.625641,4032.913751,6.893870,7588.0,12.970940,2497.0,4.268376,124.0,0.211966,550.0,0.940171,15.567,495.000,74.430,182.2695,0.026610,0.846154,0.127231,0.311572
#Dubai,43,733.0,125248.0,170.870396,16384.0,22.351978,3830.0,5.225102,1061.0,1.447476,5184.017236,7.072329,9592.0,13.085948,2976.0,4.060027,253.0,0.345157,539.0,0.735334,20.029,609.471,103.505,235.2646,0.027325,0.831475,0.141207,0.320961
#Dublin,34,974.0,154054.0,158.166324,20734.0,21.287474,5038.0,5.172485,1536.0,1.577002,6790.387427,6.971650,11519.0,11.826489,3258.0,3.344969,140.0,0.143737,644.0,0.661191,37.805,823.607,112.597,247.5192,0.038814,0.845592,0.115603,0.254126
#Dusseldorf,13,481.0,98852.0,205.513514,12590.0,26.174636,2907.0,6.043659,756.0,1.571726,3490.687404,7.257146,7978.0,16.586279,2840.0,5.904366,126.0,0.261954,426.0,0.885655,15.250,422.151,43.597,98.5358,0.031705,0.877653,0.090638,0.204856
#Geneva,7,578.0,119753.0,207.185121,15183.0,26.268166,3185.0,5.510381,902.0,1.560554,4260.996835,7.371967,9386.0,16.238754,3392.0,5.868512,156.0,0.269896,606.0,1.048443,18.712,507.822,51.474,107.6707,0.032374,0.878585,0.089055,0.186281
#Gothenburg,31,84.0,16655.0,198.273810,2013.0,23.964286,354.0,4.214286,118.0,1.404762,646.088086,7.691525,1433.0,17.059524,645.0,7.678571,25.0,0.297619,58.0,0.690476,1.186,76.601,6.215,17.9943,0.014119,0.911917,0.073988,0.214218
#Guangzhou,68,167.0,30529.0,182.808383,3964.0,23.736527,942.0,5.640719,289.0,1.730539,1379.410391,8.259942,2324.0,13.916168,714.0,4.275449,41.0,0.245509,113.0,0.676647,2.207,148.892,15.899,39.6056,0.013216,0.891569,0.095204,0.237159
#Hamburg,22,324.0,59827.0,184.651235,7802.0,24.080247,1785.0,5.509259,490.0,1.512346,2303.378584,7.109193,4984.0,15.382716,1758.0,5.425926,56.0,0.172840,262.0,0.808642,7.617,282.900,33.482,84.4405,0.023509,0.873148,0.103340,0.260619
#Hangzhou,65,145.0,30747.0,212.048276,4137.0,28.531034,968.0,6.675862,261.0,1.800000,987.447641,6.809984,2131.0,14.696552,729.0,5.027586,50.0,0.344828,91.0,0.627586,2.000,128.301,14.697,45.8307,0.013793,0.884834,0.101359,0.316074
#Hanoi,84,236.0,43393.0,183.868644,6263.0,26.538136,696.0,2.949153,291.0,1.233051,1647.032273,6.978950,3157.0,13.377119,1167.0,4.944915,39.0,0.165254,78.0,0.330508,4.908,218.959,12.134,19.1575,0.020797,0.927792,0.051415,0.081176
#Hanover,33,117.0,21182.0,181.042735,2832.0,24.205128,593.0,5.068376,203.0,1.735043,811.299035,6.934180,1619.0,13.837607,561.0,4.794872,32.0,0.273504,156.0,1.333333,5.826,100.849,10.326,15.4439,0.049795,0.861957,0.088256,0.131999
#Helsinki,2,998.0,168601.0,168.938878,19774.0,19.813627,3182.0,3.188377,1672.0,1.675351,8272.961272,8.289540,12898.0,12.923848,3531.0,3.538076,259.0,0.259519,487.0,0.487976,18.466,919.353,60.190,119.5067,0.018503,0.921195,0.060311,0.119746
#HoChiMinh,83,539.0,119236.0,221.217069,15251.0,28.294991,2735.0,5.074212,831.0,1.541744,3902.777409,7.240774,8724.0,16.185529,3296.0,6.115028,156.0,0.289425,424.0,0.786642,16.621,482.196,40.182,85.6205,0.030837,0.894612,0.074549,0.158851
#HongKong,32,999.0,186848.0,187.035035,25908.0,25.933934,7617.0,7.624625,1667.0,1.668669,6705.697141,6.712410,11199.0,11.210210,2836.0,2.838839,149.0,0.149149,909.0,0.909910,82.046,808.935,108.017,81.8892,0.082128,0.809745,0.108125,0.081971
#Hyderabad,85,946.0,195368.0,206.520085,25182.0,26.619450,5294.0,5.596195,1424.0,1.505285,6760.316685,7.146212,13449.0,14.216702,4165.0,4.402748,501.0,0.529598,1009.0,1.066596,27.342,814.806,103.859,230.4820,0.028903,0.861317,0.109788,0.243638
#Jakarta,94,210.0,37152.0,176.914286,4363.0,20.776190,413.0,1.966667,290.0,1.380952,1595.159295,7.595997,3582.0,17.057143,1397.0,6.652381,66.0,0.314286,290.0,1.380952,4.882,177.814,27.305,68.3243,0.023248,0.846733,0.130024,0.325354
#Kiev,98,202.0,39080.0,193.465347,4935.0,24.430693,524.0,2.594059,305.0,1.509901,1481.346331,7.333398,3303.0,16.351485,1281.0,6.341584,38.0,0.188119,125.0,0.618812,4.978,186.489,10.532,16.6461,0.024644,0.923213,0.052139,0.082406
#Krakow,58,423.0,74565.0,176.276596,9191.0,21.728132,877.0,2.073286,774.0,1.829787,3211.741785,7.592770,5945.0,14.054374,1618.0,3.825059,106.0,0.250591,267.0,0.631206,4.672,398.210,20.118,50.4266,0.011045,0.941395,0.047560,0.119212
#KualaLumpur,54,499.0,106121.0,212.667335,12881.0,25.813627,1563.0,3.132265,662.0,1.326653,3785.510661,7.586194,6904.0,13.835671,2449.0,4.907816,156.0,0.312625,500.0,1.002004,6.514,466.209,26.278,71.5124,0.013054,0.934287,0.052661,0.143311
#Lagos,109,991.0,208889.0,210.786075,27358.0,27.606458,5794.0,5.846620,1493.0,1.506559,6793.887384,6.855588,15618.0,15.759839,5881.0,5.934410,334.0,0.337033,1168.0,1.178607,25.064,830.574,135.364,361.5777,0.025292,0.838117,0.136593,0.364861
#Lisbon,75,600.0,123655.0,206.091667,16199.0,26.998333,4074.0,6.790000,1003.0,1.671667,4169.152504,6.948588,9548.0,15.913333,2995.0,4.991667,140.0,0.233333,459.0,0.765000,13.869,508.227,77.902,205.3027,0.023115,0.847045,0.129837,0.342171
#London,15,857.0,153420.0,179.019837,19783.0,23.084014,4446.0,5.187865,1273.0,1.485414,6211.417076,7.247861,12240.0,14.282380,3934.0,4.590432,223.0,0.260210,666.0,0.777130,22.934,745.145,88.912,213.7601,0.026761,0.869481,0.103748,0.249428
#LosAngeles,26,856.0,164200.0,191.822430,20105.0,23.487150,3978.0,4.647196,1322.0,1.544393,6460.175734,7.546934,13506.0,15.778037,5212.0,6.088785,154.0,0.179907,970.0,1.133178,29.006,735.092,91.892,199.8320,0.033886,0.858752,0.107350,0.233449
#Lyon,51,548.0,93212.0,170.094891,13159.0,24.012774,2893.0,5.279197,867.0,1.582117,3445.465664,6.287346,6641.0,12.118613,2784.0,5.080292,174.0,0.317518,365.0,0.666058,23.491,467.702,56.802,107.1858,0.042867,0.853471,0.103653,0.195595
#Madrid,45,902.0,128097.0,142.014412,17602.0,19.514412,4364.0,4.838137,1341.0,1.486696,6021.501546,6.675722,9227.0,10.229490,2654.0,2.942350,129.0,0.143016,580.0,0.643016,77.455,751.752,72.798,-30.5125,0.085870,0.833428,0.080707,-0.033828
#Makassar,96,112.0,21287.0,190.062500,2386.0,21.303571,64.0,0.571429,145.0,1.294643,928.147895,8.287035,1746.0,15.589286,826.0,7.375000,41.0,0.366071,124.0,1.107143,1.414,104.193,6.392,13.4396,0.012625,0.930295,0.057071,0.119996
#Manchester,17,1876.0,351143.0,187.176439,46399.0,24.732942,11965.0,6.377932,2734.0,1.457356,13216.508701,7.045047,24967.0,13.308635,7961.0,4.243603,517.0,0.275586,1368.0,0.729211,60.280,1584.861,230.861,547.9834,0.032132,0.844809,0.123060,0.292102
#Manila,104,267.0,49565.0,185.636704,6168.0,23.101124,991.0,3.711610,428.0,1.602996,2003.605226,7.504139,4120.0,15.430712,1579.0,5.913858,65.0,0.243446,276.0,1.033708,6.333,236.300,24.369,62.7207,0.023719,0.885019,0.091270,0.234909
#Marseille,78,396.0,65056.0,164.282828,8948.0,22.595960,1223.0,3.088384,572.0,1.444444,2677.050093,6.760228,4915.0,12.411616,1512.0,3.818182,165.0,0.416667,311.0,0.785354,10.650,355.195,30.151,69.9271,0.026894,0.896957,0.076139,0.176584
#Medan,97,71.0,11892.0,167.492958,1406.0,19.802817,144.0,2.028169,92.0,1.295775,560.789801,7.898448,1096.0,15.436620,517.0,7.281690,17.0,0.239437,46.0,0.647887,3.113,61.646,6.238,7.8143,0.043845,0.868254,0.087859,0.110061
#Medellin,72,850.0,132224.0,155.557647,16525.0,19.441176,1134.0,1.334118,1095.0,1.288235,6894.177441,8.110797,10050.0,11.823529,3131.0,3.683529,360.0,0.423529,492.0,0.578824,18.202,801.295,30.492,35.1558,0.021414,0.942700,0.035873,0.041360
#Melbourne,20,866.0,159753.0,184.472286,20872.0,24.101617,5080.0,5.866051,1345.0,1.553118,6123.512928,7.071031,11688.0,13.496536,3961.0,4.573903,206.0,0.237875,539.0,0.622402,22.905,730.568,112.532,280.2786,0.026449,0.843612,0.129945,0.323647
#MexicoCity,90,654.0,125086.0,191.262997,15536.0,23.755352,3092.0,4.727829,980.0,1.498471,4984.077758,7.620914,9768.0,14.935780,3609.0,5.518349,143.0,0.218654,544.0,0.831804,19.032,577.217,57.750,118.8426,0.029101,0.882595,0.088303,0.181717
#Milan,74,600.0,101778.0,169.630000,13231.0,22.051667,2424.0,4.040000,837.0,1.395000,4165.550995,6.942585,8727.0,14.545000,3590.0,5.983333,182.0,0.303333,567.0,0.945000,15.811,520.368,63.823,136.7903,0.026352,0.867280,0.106372,0.227984
#Montreal,21,1231.0,217733.0,176.874898,28502.0,23.153534,6548.0,5.319253,1886.0,1.532088,8600.784963,6.986828,16683.0,13.552396,5548.0,4.506905,262.0,0.212835,1125.0,0.913891,53.556,1046.145,131.296,248.4368,0.043506,0.849833,0.106658,0.201817
#Moscow,56,898.0,167425.0,186.442094,22985.0,25.595768,6246.0,6.955457,1406.0,1.565702,5927.568704,6.600856,11542.0,12.853007,4010.0,4.465479,182.0,0.202673,586.0,0.652561,71.519,766.191,60.305,-21.4324,0.079643,0.853219,0.067155,-0.023867
#Mumbai,93,1000.0,178179.0,178.179000,23005.0,23.005000,4424.0,4.424000,1398.0,1.398000,7050.894369,7.050894,13770.0,13.770000,4574.0,4.574000,375.0,0.375000,794.0,0.794000,42.421,843.819,113.734,209.5061,0.042421,0.843819,0.113734,0.209506
#Munich,11,1000.0,203658.0,203.658000,26300.0,26.300000,6017.0,6.017000,1596.0,1.596000,7095.979932,7.095980,16508.0,16.508000,6475.0,6.475000,261.0,0.261000,803.0,0.803000,21.182,881.644,97.181,277.6577,0.021182,0.881644,0.097181,0.277658
#Nairobi,108,918.0,180787.0,196.935730,23967.0,26.107843,5676.0,6.183007,1388.0,1.511983,6167.190845,6.718073,12693.0,13.826797,4554.0,4.960784,292.0,0.318083,946.0,1.030501,32.457,781.523,104.019,250.6912,0.035356,0.851332,0.113310,0.273084
#Nanjing,66,593.0,122333.0,206.295110,16247.0,27.397976,3807.0,6.419899,1006.0,1.696459,4226.732072,7.127710,9169.0,15.462057,2925.0,4.932546,219.0,0.369309,584.0,0.984823,17.528,517.523,57.952,137.3918,0.029558,0.872720,0.097727,0.231689
#New York,10,191.0,34243.0,179.282723,4447.0,23.282723,643.0,3.366492,252.0,1.319372,1339.963266,7.015514,3094.0,16.198953,1062.0,5.560209,60.0,0.314136,278.0,1.455497,6.204,167.931,16.869,30.4982,0.032482,0.879220,0.088319,0.159676
#Newcastle,23,973.0,193512.0,198.881809,26636.0,27.375128,6930.0,7.122302,1513.0,1.554985,6354.124566,6.530447,13667.0,14.046249,3982.0,4.092497,224.0,0.230216,1060.0,1.089414,32.100,826.409,114.492,296.6392,0.032991,0.849341,0.117669,0.304871
#NewDelhi,86,761.0,162550.0,213.600526,20403.0,26.810775,4632.0,6.086728,1073.0,1.409987,5508.107828,7.237987,11830.0,15.545335,3851.0,5.060447,219.0,0.287779,660.0,0.867280,26.107,666.678,68.214,140.7269,0.034306,0.876055,0.089637,0.184924
#Osaka,80,237.0,45105.0,190.316456,5704.0,24.067511,1038.0,4.379747,317.0,1.337553,1771.704627,7.475547,4184.0,17.654008,1809.0,7.632911,54.0,0.227848,191.0,0.805907,3.875,203.586,29.541,73.8458,0.016350,0.859013,0.124646,0.311586
#Oslo,5,1000.0,191611.0,191.611000,25104.0,25.104000,5375.0,5.375000,1648.0,1.648000,6979.791232,6.979791,15615.0,15.615000,5781.0,5.781000,200.0,0.200000,830.0,0.830000,27.391,852.592,120.023,282.7422,0.027391,0.852592,0.120023,0.282742
#Paris,61,760.0,125829.0,165.564474,15718.0,20.681579,3013.0,3.964474,1085.0,1.427632,5569.781058,7.328659,10745.0,14.138158,4137.0,5.443421,163.0,0.214474,470.0,0.618421,27.599,647.970,84.429,151.0793,0.036314,0.852592,0.111091,0.198789
#Philadelphia,52,786.0,149148.0,189.755725,19116.0,24.320611,4387.0,5.581425,1239.0,1.576336,5676.033098,7.221416,11044.0,14.050891,3778.0,4.806616,220.0,0.279898,1150.0,1.463104,24.549,678.773,82.681,186.3178,0.031233,0.863579,0.105192,0.237046
#Phoenix,39,592.0,97044.0,163.925676,13225.0,22.339527,3215.0,5.430743,973.0,1.643581,3954.009700,6.679070,7663.0,12.944257,2451.0,4.140203,99.0,0.167230,738.0,1.246622,23.194,505.992,62.806,132.1309,0.039179,0.854716,0.106091,0.223194
#Prague,44,473.0,85922.0,181.653277,10790.0,22.811839,2011.0,4.251586,740.0,1.564482,3620.197483,7.653694,7327.0,15.490486,2753.0,5.820296,124.0,0.262156,302.0,0.638478,7.323,424.842,40.833,108.0771,0.015482,0.898186,0.086328,0.228493
#Rabat,105,137.0,26401.0,192.708029,3486.0,25.445255,297.0,2.167883,191.0,1.394161,953.630089,6.960804,2094.0,15.284672,820.0,5.985401,49.0,0.357664,88.0,0.642336,1.488,130.271,5.242,10.3748,0.010861,0.950883,0.038263,0.075728
#RiodeJaneiro,102,590.0,103613.0,175.615254,12560.0,21.288136,1242.0,2.105085,791.0,1.340678,4691.927868,7.952420,8561.0,14.510169,3571.0,6.052542,94.0,0.159322,594.0,1.006780,17.198,537.816,34.992,57.5187,0.029149,0.911553,0.059308,0.097489
#Riyadh,53,358.0,70199.0,196.086592,8902.0,24.865922,1862.0,5.201117,492.0,1.374302,2598.125651,7.257334,5538.0,15.469274,2154.0,6.016760,76.0,0.212291,285.0,0.796089,7.222,309.712,41.063,105.2204,0.020173,0.865117,0.114701,0.293912
#Rome,101,1000.0,178089.0,178.089000,23453.0,23.453000,5482.0,5.482000,1644.0,1.644000,7186.268235,7.186268,15200.0,15.200000,5201.0,5.201000,184.0,0.184000,661.0,0.661000,28.062,876.279,95.677,209.8256,0.028062,0.876279,0.095677,0.209826

In [51]:
sc100_features = sc100_features.drop(columns=['total_tweet_len','total_num_words','total_stopwords','total_num_sentences','total_avg_word_len','total_punctuation','total_hashtags','total_numerics','total_upper','neg','neu','pos','compound'])

In [52]:
# create a new column with lists of merged tweets grouped by city
sc100_features = pd.concat([sc100_features, smartcities100.groupby('query')['content'].apply(lambda x: x.tolist())], axis=1)

In [53]:
# convert the merged tweets lists into strings
sc100_features['content'] = sc100_features['content'].apply(lambda x: str(x).strip('[]'))

In [54]:
# count number of words for each city
sc100_features['words'] = sc100_features['content'].apply(lambda x: len(x))

In [55]:
# count number of stopwords for each city
sc100_features['stopwords'] = sc100_features['content'].apply(lambda x: len([x for x in x.split() if x in stop]))

In [56]:
# count number of punctuation for each city
sc100_features['punctuation'] = sc100_features['content'].apply(lambda x: count_punct(x))

In [57]:
# count number of hashtags for each city
sc100_features['hashtags'] = sc100_features['content'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))

In [58]:
# count number of numerics for each city
sc100_features['numerics'] = sc100_features['content'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))

In [59]:
# count number of uppercase words for each city
sc100_features['upper'] = sc100_features['content'].apply(lambda x: len([x for x in x.split() if x.isupper()]))

# cleaning tweets merged

In [60]:
# create a new column to lower characters of tweets merged
sc100_features['clean_text'] = sc100_features['content'].apply(lambda x: x.lower())

In [61]:
# convert emojis into words
def convert_emojis(text):
    for emot in UNICODE_EMO:
        text = text.replace(emot, "_".join(UNICODE_EMO[emot].replace(",","").replace(":","").split()))
    return text

sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: convert_emojis(x))

In [62]:
# convert emoticons into words
def convert_emoticons(text):
    for emot in EMOTICONS:
        text = re.sub(u'('+emot+')', "_".join(EMOTICONS[emot].replace(",","").split()), text)
    return text

sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: convert_emoticons(x))

In [63]:
# remove punctuation
sc100_features['clean_text'] = sc100_features['clean_text'].str.replace('[^\w\s]','')

In [64]:
#remove symbols
sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: re.sub(r'.,;?!/\&*$€£`§"+-%|:_’`()','', str(x)))

In [65]:
# remove stopwords
sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

In [66]:
# remove urls
def remove_url(text):
    url = re.compile(r'https?://\S+|www\.\S+')
    return url.sub(r'', text)

sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: remove_url(x))

In [67]:
# remove htmls
def remove_html(text):
    html=re.compile(r'<.*?>')
    return html.sub(r'',text)

sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: remove_html(x))

In [68]:
# remove # 
import re
sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: re.sub(r'#',' ', x))

In [69]:
# remove @mentions
sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: re.sub(r'@[A-Za-z0-9]+','', str(x)))

In [70]:
#remove digits
sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: re.sub(r'[0-9]+','', str(x)))

In [71]:
# expand contractions 
contractions = contractions = { 
"ain't": "am not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he'll've": "he will have",
"he's": "he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how is",
"I'd": "I would",
"I'd've": "I would have",
"I'll": "I will",
"I'll've": "I will have",
"I'm": "I am",
"I've": "I have",
"isn't": "is not",
"it'd": "it would",
"it'd've": "it would have",
"it'll": "it will",
"it'll've": "it will have",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she would",
"she'd've": "she would have",
"she'll": "she will",
"she'll've": "she will have",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as / so is",
"that'd": "that would",
"that'd've": "that would have",
"that's": "that is",
"there'd": "there would",
"there'd've": "there would have",
"there's": "there is",
"they'd": "they would",
"they'd've": "they would have",
"they'll": "they will",
"they'll've": "they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what'll've": "what will have",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"when's": "when is",
"when've": "when have",
"where'd": "where did",
"where's": "where is",
"where've": "where have",
"who'll": "who will",
"who'll've": "who will have",
"who's": "who is",
"who've": "who have",
"why's": "why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you would",
"you'd've": "you would have",
"you'll": "you will",
"you'll've": "you will have",
"you're": "you are",
"you've": "you have"
}
def cont_to_exp(x):
    if type(x) is str:
        x = x.replace('\\','')
        for key in contractions:
            value = contractions[key]
            x = x.replace(key,value)
        return x
    else:
        return x

sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: cont_to_exp(x))

# too long, to fix : spell correction
sc100_features['clean_text'] = sc100_features['clean_text'].apply(lambda x: str(TextBlob(x).correct()))

In [73]:
# count number of clean words
sc100_features['num_clean_words'] = sc100_features['clean_text'].apply(lambda x: len(str(x).split(" ")))

In [74]:
# count number of characters into clean text (incl. spaces)
sc100_features['num_clean_characters'] = sc100_features['clean_text'].str.len()

In [75]:
# average word length for clean words
def avg_word(sentence):
    words = sentence.split()
    return (sum(len(word) for word in words)/(len(words)+0.000001))

sc100_features['avg_clean_word_len'] = sc100_features['clean_text'].apply(lambda x: avg_word(x)).round(1)

In [76]:
# tokenize clean text into a dedicated column
sc100_features['tokens'] = sc100_features['clean_text'].apply(lambda x: nltk.word_tokenize(x))

In [77]:
#remove useless tokens
useless = ["com","#",'&','!',"gt","'re","\n","amp","als","'s","als", "etc",'\n', "\\n",'\\n\\n',']','[','.','...','“',',',"'","''",'th','…','“',':']

sc100_features['tokens'] = sc100_features['tokens'].apply(lambda x: [item for item in x if item not in useless])

In [78]:
# count most freq 100 words for each city
sc100_features['most_freq100'] = sc100_features['tokens'].apply(lambda x: FreqDist(x).most_common(100))

In [79]:
# Remove NaN row and reset index
sc100_features = sc100_features.reset_index().dropna()

In [80]:
# check my dataframe
sc100_features.head()

,index,min,query,avg_tweet_len,avg_num_words,avg_stopwords,avg_num_sentences,avg_avg_word_len,avg_punctuation,avg_hashtags,avg_numerics,avg_upper,avg_neg,avg_neu,avg_pos,avg_compound,content,words,stopwords,punctuation,hashtags,numerics,upper,clean_text,num_clean_words,num_clean_characters,avg_clean_word_len,tokens,most_freq100
0,#AbuDhabi,42,832.0,193.930288,25.002404,5.794471,1.435096,7.076026,14.016827,4.602163,0.278846,1.091346,0.021933,0.860132,0.117936,0.299883,'A Delegation from @aau_ae visited @BurjeelMe...,166602,4811,15703,3268,202,760,delegation aau_ae visited burjeelmedicity one ...,14484,173030,11.2,"[delegation, aau_ae, visited, burjeelmedicity,...","[(abudhabi, 677), (uae, 224), (abu, 156), (dub..."
1,#Abuja,107,828.0,209.646135,27.042271,5.580918,1.437198,7.075491,15.369565,5.787440,0.404589,1.263285,0.018193,0.856400,0.125396,0.356573,"'Brother #Abuja https://t.co/6J3yOIP8Jm', 'Our...",180295,4561,18553,3862,232,766,brother abuja httpsSkeptical_annoyed_undecided...,15083,182674,11.4,"[brother, abuja, httpsSkeptical_annoyed_undeci...","[(abuja, 635), (lagos, 163), (abujatwittercomm..."
2,#Amsterdam,9,1000.0,180.311000,22.627000,5.220000,1.520000,7.579219,14.554000,5.239000,0.153000,0.663000,0.024567,0.875009,0.100439,0.250798,'Herfst in #Amsterdam 🍂🍃🍁 https://t.co/F0VKRmq...,185912,5200,18994,4740,134,563,herfst amsterdam fallen_leafleaf_fluttering_in...,15579,197584,11.9,"[herfst, amsterdam, fallen_leafleaf_fluttering...","[(amsterdam, 993), (netherlands, 80), (day, 64..."
3,#Ankara,57,313.0,185.808307,22.984026,3.974441,1.306709,7.510589,14.747604,5.623003,0.338658,0.840256,0.039681,0.865914,0.094422,0.192013,'I had a great and very joyful flight today ✈️...,60230,1241,6328,1426,77,224,great joyful flight today airplane nto ankara ...,5302,66000,11.7,"[great, joyful, flight, today, airplane, nto, ...","[(ankara, 251), (turkey, 77), (turkish, 26), (..."
4,#Athens,99,1000.0,186.752000,24.268000,5.405000,1.503000,7.170592,15.201000,5.442000,0.226000,0.865000,0.042164,0.865646,0.092190,0.176392,'Georgia GA #GARunoffs\n#Sparta #Athens #Ciara...,192839,5370,20229,4795,180,766,georgia ga garunoffsnsparta athens ciara lukes...,16782,204722,11.5,"[georgia, ga, garunoffsnsparta, athens, ciara,...","[(athens, 867), (greece, 322), (greek, 74), (a..."

In [81]:
# clean column names
sc100_features.columns = ['city_id', 'rank2020', 'num_tweets','avg_tweet_len', 'avg_num_words','avg_stopwords', 'avg_num_sentences', 'avg_word_len', 'avg_punctuation', 'avg_hashtags', 'avg_numerics', 'avg_upper', 'avg_neg', 'avg_neu', 'avg_pos', 'avg_compound', 'tweets_merged', 'total_words', 'total_stopwords', 'total_punctuation','total_hashtags','total_numerics','total_upper','clean_text','total_clean_words','total_clean_char','avg_clean_word_len','tokens','most_freq100']
sc100_features.head()

,city_id,rank2020,num_tweets,avg_tweet_len,avg_num_words,avg_stopwords,avg_num_sentences,avg_word_len,avg_punctuation,avg_hashtags,avg_numerics,avg_upper,avg_neg,avg_neu,avg_pos,avg_compound,tweets_merged,total_words,total_stopwords,total_punctuation,total_hashtags,total_numerics,total_upper,clean_text,total_clean_words,total_clean_char,avg_clean_word_len,tokens,most_freq100
0,#AbuDhabi,42,832.0,193.930288,25.002404,5.794471,1.435096,7.076026,14.016827,4.602163,0.278846,1.091346,0.021933,0.860132,0.117936,0.299883,'A Delegation from @aau_ae visited @BurjeelMe...,166602,4811,15703,3268,202,760,delegation aau_ae visited burjeelmedicity one ...,14484,173030,11.2,"[delegation, aau_ae, visited, burjeelmedicity,...","[(abudhabi, 677), (uae, 224), (abu, 156), (dub..."
1,#Abuja,107,828.0,209.646135,27.042271,5.580918,1.437198,7.075491,15.369565,5.787440,0.404589,1.263285,0.018193,0.856400,0.125396,0.356573,"'Brother #Abuja https://t.co/6J3yOIP8Jm', 'Our...",180295,4561,18553,3862,232,766,brother abuja httpsSkeptical_annoyed_undecided...,15083,182674,11.4,"[brother, abuja, httpsSkeptical_annoyed_undeci...","[(abuja, 635), (lagos, 163), (abujatwittercomm..."
2,#Amsterdam,9,1000.0,180.311000,22.627000,5.220000,1.520000,7.579219,14.554000,5.239000,0.153000,0.663000,0.024567,0.875009,0.100439,0.250798,'Herfst in #Amsterdam 🍂🍃🍁 https://t.co/F0VKRmq...,185912,5200,18994,4740,134,563,herfst amsterdam fallen_leafleaf_fluttering_in...,15579,197584,11.9,"[herfst, amsterdam, fallen_leafleaf_fluttering...","[(amsterdam, 993), (netherlands, 80), (day, 64..."
3,#Ankara,57,313.0,185.808307,22.984026,3.974441,1.306709,7.510589,14.747604,5.623003,0.338658,0.840256,0.039681,0.865914,0.094422,0.192013,'I had a great and very joyful flight today ✈️...,60230,1241,6328,1426,77,224,great joyful flight today airplane nto ankara ...,5302,66000,11.7,"[great, joyful, flight, today, airplane, nto, ...","[(ankara, 251), (turkey, 77), (turkish, 26), (..."
4,#Athens,99,1000.0,186.752000,24.268000,5.405000,1.503000,7.170592,15.201000,5.442000,0.226000,0.865000,0.042164,0.865646,0.092190,0.176392,'Georgia GA #GARunoffs\n#Sparta #Athens #Ciara...,192839,5370,20229,4795,180,766,georgia ga garunoffsnsparta athens ciara lukes...,16782,204722,11.5,"[georgia, ga, garunoffsnsparta, athens, ciara,...","[(athens, 867), (greece, 322), (greek, 74), (a..."

In [82]:
# clean city_id by removing # using regex
sc100_features['city_id'] = sc100_features['city_id'].apply(lambda x: re.sub(r'#','', str(x)))

In [83]:
# lower characters
sc100_features['city_id'] = sc100_features['city_id'].str.lower()

In [84]:
sc100_features['num_tweets'] = sc100_features['num_tweets'].apply(np.int64)
sc100_features.head()

,city_id,rank2020,num_tweets,avg_tweet_len,avg_num_words,avg_stopwords,avg_num_sentences,avg_word_len,avg_punctuation,avg_hashtags,avg_numerics,avg_upper,avg_neg,avg_neu,avg_pos,avg_compound,tweets_merged,total_words,total_stopwords,total_punctuation,total_hashtags,total_numerics,total_upper,clean_text,total_clean_words,total_clean_char,avg_clean_word_len,tokens,most_freq100
0,abudhabi,42,832,193.930288,25.002404,5.794471,1.435096,7.076026,14.016827,4.602163,0.278846,1.091346,0.021933,0.860132,0.117936,0.299883,'A Delegation from @aau_ae visited @BurjeelMe...,166602,4811,15703,3268,202,760,delegation aau_ae visited burjeelmedicity one ...,14484,173030,11.2,"[delegation, aau_ae, visited, burjeelmedicity,...","[(abudhabi, 677), (uae, 224), (abu, 156), (dub..."
1,abuja,107,828,209.646135,27.042271,5.580918,1.437198,7.075491,15.369565,5.787440,0.404589,1.263285,0.018193,0.856400,0.125396,0.356573,"'Brother #Abuja https://t.co/6J3yOIP8Jm', 'Our...",180295,4561,18553,3862,232,766,brother abuja httpsSkeptical_annoyed_undecided...,15083,182674,11.4,"[brother, abuja, httpsSkeptical_annoyed_undeci...","[(abuja, 635), (lagos, 163), (abujatwittercomm..."
2,amsterdam,9,1000,180.311000,22.627000,5.220000,1.520000,7.579219,14.554000,5.239000,0.153000,0.663000,0.024567,0.875009,0.100439,0.250798,'Herfst in #Amsterdam 🍂🍃🍁 https://t.co/F0VKRmq...,185912,5200,18994,4740,134,563,herfst amsterdam fallen_leafleaf_fluttering_in...,15579,197584,11.9,"[herfst, amsterdam, fallen_leafleaf_fluttering...","[(amsterdam, 993), (netherlands, 80), (day, 64..."
3,ankara,57,313,185.808307,22.984026,3.974441,1.306709,7.510589,14.747604,5.623003,0.338658,0.840256,0.039681,0.865914,0.094422,0.192013,'I had a great and very joyful flight today ✈️...,60230,1241,6328,1426,77,224,great joyful flight today airplane nto ankara ...,5302,66000,11.7,"[great, joyful, flight, today, airplane, nto, ...","[(ankara, 251), (turkey, 77), (turkish, 26), (..."
4,athens,99,1000,186.752000,24.268000,5.405000,1.503000,7.170592,15.201000,5.442000,0.226000,0.865000,0.042164,0.865646,0.092190,0.176392,'Georgia GA #GARunoffs\n#Sparta #Athens #Ciara...,192839,5370,20229,4795,180,766,georgia ga garunoffsnsparta athens ciara lukes...,16782,204722,11.5,"[georgia, ga, garunoffsnsparta, athens, ciara,...","[(athens, 867), (greece, 322), (greek, 74), (a..."

# extract weigh of BoW for each city_id

In [85]:
# define data transformations
stemmer = PorterStemmer()

def stem_tokens(tokens, stemmer):
    stemmed = []
    for item in tokens:
        stemmed.append(stemmer.stem(item))
    return stemmed

def tokenize(text):
    tokens = word_tokenize(text)
    stems = stem_tokens(tokens, stemmer)
    return stems

vect = CountVectorizer(tokenizer=tokenize, stop_words='english')

# define each BoW as a list of thematic words (Lexicons)
smartcity = ['digitaltransformation','2.0','smartcity','iot','smart','city','ai','smartcities','innovation','cities','5g','data','bigdata','technology','future','tech','digital','digitaltransformation','machinelearning','analytics','solutions','cloud','datascience','network','security','cybersecurity','urban','people','artificialintelligence','smarthome','internetofthings','autonomous','smart','technologies','robotics','software','research','monitoring','street','sensors','futureofwork','planning','governance','transportation','safecity','building','robot','industry40','startups','development','smartthings','urbanplanning','connected','internet','sustainable','waste','emergingtech','programming','environment','safety','lighting','safety','roads','workplaces','smartbuildings','driverless','selfdriving','smartmobility','futureworkspace','digitalcity','deeplearning','datadriven','application','robots','publicsafety','energyefficiency','labgov','citizens','transformation','controlroom','publicspace','airquality','efficiency','era','smarter','urbaninnovation','internetofeverything','newtown','iotforall','construction','privacy','surveillance','drones','smartbuilding','smartgrid','smartgrids','cybersecurity','policy','powergrid','smartcities','iot','electricity','smartmetering','smartmeters','technology','microgrids','microgrid','smartcity','powergrids','iot','ai','machinelearning','bigdata','serverless','cybersecurity','devcommunity','programming','coding','cloudcomputing','codenewbie','100daysofmlcode','womenintech','innovation','deeplearning','security','machine','digital','industrial','artificial','computing','robot','wearables','artificial','networks','drones','connectivity','wireless','urbanplanning','city','urban','cities','smartcities','architecture','urbanism','urbandesign','cityplanning','urbanization','futurecities','urbaninnovation','bigdata','cityplanner','architects','citylab','urbanplanner','urbanplanners','cityplanners','urbandata','townplanning','planners','neighborhoods','sustainablecities','tacticalurbanism','urbanmobility','pedestrians','neighborhood','citiesforpeople','neighbourhood','rethinkreplace','constructionmanagement','suburban','futurecity','cityvisionnaire','smarttechnology','citygoals','civilengineering','digitaltwin','bigdata','digitaltransformation','pedestrian-friendly','surveillance','technologies','urbandevelopment','cities','urban','urbanplanning'] 
civictech = ['aiethics','empowerment','learned','communityengagement','communitydevelopment','nonprofit','notforprofit','collaboration','vulnerable','diversity','egov','egovernance','inclusion','ethics','social','engagement','crowdsourcing','humanrights','citizenship','civic','opendata','referendum','rights','citizens','open','social','people','sharingeconomy','hack','citizens','communities','civictech','inequalities','equity','participatory','social','youthempowerment','govtech','localgov','civic','stateandlocal','community','governmentit','statelocalit','opendata','sharing','including','volunteer','social','people','shared','learn','opengov','localgovernment','education','hackathon','civictechto','techforgood','discussion','communities','local','digitalgov','future','online','governments','webmapping','capacity','accessibility','discuss','ethics','citizens','together','initiative','transparency','data4good','publicinteresttech','democracy','volunteers','society','makers','ecitizenship','eresidency','citizenship','egovernment','esafety','digitaltransformation','policy','social','technology','future','citizen','ecivility','digitaleconomy','ideagov','egov','people','edemocracy','eparticipation','education','citizens','progressive','security','ecitizenship','inclusive','watch','startups','concept','digitalnation','netgov','app','privacy','egovernance','tool','democratic','eublockchain','digitaleu','digitalnomad','apps','residents','populationeu','migrationpolicy','migrationsystem','migration','voted','govtech','smartcities','humandevelopment','erisks','ecitizen','artificial','intelligence','opendata','empowerment','leadership','growth','success','youth','wisdom','education','relationship','powerinpurpose','community','beyondlimits','powerwithin','support','empower','empowering','equality','enlightment','selfdiscovery','confidence','selfempowerment','leaders','forward','diversity','empowered','successmindset','cybersecurity','government','security','technology','opendata','open','openscience','opensource','opendataday','community','citizenscience','citizen','citizenship','openaccess','transparence','openbanking','womenwhocode','openapis','policy','grants','decisions','institutions','opengov','social','busopendata','datadriven','citizen','openstreetmap','researchdata','engagement','citizens']
infrastructure = ['supply','platform','blockchain','system','internet','battery','batterystorage','energystorage','mobility','storage','blockchain','serverless','grids','blockchain','standards','realestate','construction','driverless','selfdriving','smartmobility','transportation','roads', 'building','traffic','autonomousvehicles','streets','platform','transportation','road','publicspace','realestate','monuments','housing','selfdrivingcars','high-speed','real-estate','mobility','highways','transportation','transport','automotive','transit','buses','cars','futureofmobility','car','travel','publictransport','autonomous','bus','auto','shared','traffic','delivery','emissions','5g','services','connectivity','van','trucks','vehicles','commute','electricvehicles','smartmobility','vehicle','logistics','multimodal','connected','metropolitan','efficiency','monitoring','providers','mobile','futurride','autonomousvehicle','engineer','seat','robotics','parking','cycling','driver','flying','rail','moving','wheelchair','automobile','walks','electricvehicle','electriccars','platform','cctv','drivers','driverless','systems','roads','drones','aviation','selfdriving','robots','electriccar','device','bike','autos','urbanmobility','speed','selfdrivingcars','network','street','urbanplanning','autocar','drive','electrification','streets','driverlesscars','bicycle','zero-emission','engineering','artificialintelligence','emobility','fleet','scooters','bikes','journey','manufacturers','route','logistics','driver','trucking','delivery','shipping','traffic','transport','freight','rentals','road','drivers','bus','mobility','rail','cargo','cars','trucks','trucker','fleet','mechanic','infrastructure','railways','diesel','taxi','truckdriver','truckers','shipments','driving','flights','pickup','airfreight','intelligentlogistics','bicycle','cycling','port','wheels','motors','machinery','ferry','infrastructure','bridge','network','architecture','building','construction','transport','metro','roads','highways','railways','realestate','housing','train','civilengineering','airport','station','connectivity','stations','tunnel','airports','equipment','bridges','km','electrical','highway','tunnels','road']
sustainability = ['resource','resources','sustainablefinance','cyberresilience','recycling','resilient','batteries','emission','resilience','energytransition','sustainability','biodiversity','sustainabledevelopment','resources','sustainableurbanplanning','sustainabletransport','sustainable','environment','climatechange','energy','climate','innovation','circulareconomy','environmental','ecofriendly','nature','planet','carbon','recycling','climateaction','plastic','renewableenergy','zerowaste','water','waste','solar','agriculture','recycle','savetheplanet','pollution','emissions','sustainablefashion','hydrogen','eco','sustainableliving','reuse','clean','recycled','greenliving','renewable','circular','gogreen','biodiversity','sustainable','renewables','climatecrisis','organic','eco-friendly','earth','sustainabledevelopment','electric','electricity','efficiency','electricvehicles','recyclable','footprint','sustainablefinance','ocean','greener','co2','plasticfree','climateemergency','greenenergy','waterconservation','carbonfootprint','greenbuilding','energytransition','sustainablity','consumption','globalwarming','resilience','reusable','battery','decompose','aquaculture','oil','compost','circularity','plastics','environment','ecoconscious','savetheplanet','green_action','eco-outreach','eco-friendly','environmental_activism','climateactivism','energyefficiency','agtech','reduction','lessismore','responsibility','🌍','cleanup','cleantech','ethical','sustainably','ecofashion','foodtech','emobility','ecosystem','passivehouse','farmtotable','nature','wildlife','planet','ecofriendly','trees','conservation','climatecrisis','savetheplanet','clean','recycle','natural','biodiversity','tree','plants','emissions','reduce','ecology','zerowaste','forests','globalwarming','garden','species','gogreen','farming','agriculture','eco','plasticpollution','soil','greener','plasticfree','farmers','extinction','reuse','recycled','renewableenergy','circulareconomy','environmentally','deforestation','oceans','fuel','naturelovers','microplastics','airpollution','rivers','plastics','renewables','climateemergency','gas','sustainablefashion','environmentaljustice','eco-friendly','bees','fossil','wastewater','fornature','wildfires','greenhouse','ecosystems','renewables','oilandgas','hydrogen','cleanenergy','greenspaces','resilience','climateemergency','sustainablemobility','sustainabledevelopment','naturebasedsolutions','energyefficiency','actonclimate','solar','renewableenergy','alternativeenergy','solarpower','sustainable','environment','solarpanels','solarpv','scienceandenvironment','solarsystems','solarenergy','energymanagement','greennewdeal','solarenergy']
governance = ['partnership','strategies','leadership','responsibility','regulations','ceo','policy','democracy2.0','elections','voter','collaboration','gov','governance','planning','management','localgov','project','partnership','partners','partner','leader','leaders','politicalparties','administration','decentralized','democracy2.0','political','society','minister','vision','crossbordercooperation','political','politics','democratic','government','politicians','elections','voter','public','commonwealth','politicalprogress','voting','debate','national','votingawareness','president','mayor','governance','parliament','campaign','liquiddemocracy','voters','brigade','constitutional','law','country','legalhack','decentralization','representatives','communityactivity','republican','policing','policy','policies','administration','governance','leadership','management','security','cybersecurity','ceo','corpgov','government','public','strategy','corruption','democracy','boardofdirectors','cio','policy','technology','leaders','boards','role','members','report','planning','throwback','organizations','national','directorship','structures','trust','directors','decentralized','countries','chair','discussion','conference','transparency','compensationcommittee','auditcommittee','cto','visionarytalks','riskmanagement','organisations','office','legal','regulations','audit','insights','corporategovernance','organization','voting','governing','organisation','policies','project','executive','responsible','leader','survey','interview','approach','staff','benefits','recruitment','regulatory','reporting','severity','obstacle','presidential','country','elections','institutions','alternative','digitaltransformation','freedom','nation','datavault','datawarehouse','regulation','processes','foundation','critical','control','candidate','promised','inauguration','anticorruption','executives','publicpolicy','principles','strategic','sharing','governments','federated','elected','framework','schedule','risks','certificate','meritocracy','stakeholders','partnership','society','equality','decisions','structure','implement','commitment','decision','driven','citiesalliance','assessment','corporations','cryptocurrencies','dataprotection']
entrepreneurship = ['freemarket','investors','crypto','financial','accountability','enterprise','assetmanagement','accountable','company','finance','corporate','contractors','workforce','digitalbanking','entrepreneur','newmarket','investment', 'market','coding','startup','development','maker','fintech','economy','business','economic','finance','markets','investing','stocks','investment','gdp','money','financial','economics','trade','crypto','businesses','investors','retail','bitcoin','employment','job','startups','growth','work','entrepreneur','unemployment','entrepreneurship','sales','manufacturing','working','corporate','companies','funds','jobless','cryptocurrency','economicrecovery','smallbusiness','workers','investments','traders','budget','assets','growing','industries','asset','invest','startup','funding','development','currency','banks','monetary','debt','skills','fintech','fiscal','entrepreneurs','deficit','banking','benefits','rates','paying','billing','billingsoftware','earnings','workfromhome','accounting','personalfinance','ratings','accountant','treasury','equities','subsidies','opportunities','profits','stockstowatch','branding','marketing','customer','firms','localbusiness','capitalism','consumers','startup','startups','innovation','mindset','smallbusiness','businessowner','entrepreneurlife','digitalmarketing','management','founder','branding','growth','company','founders','funding','product','businesses','businessgrowth','sales','coaching','investment','entrepreneurial','venture','businessangel','capital','smallbusinessowner','businessman','customers','businesscoach','speaker','finance','market','skills','coding','ecommerce','entrepreneurmindset','startuplife','pitch','onlinebusiness','employment','businesswoman','socialmediamarketing','girlswhocode','crypto','womeninbusiness','investors','selfemployment','accelerator','incubator','designthinking','growthhacking','enterprise','changemakers','startupbusiness','businessideas','mentors','businesscoaching','businessmotivation','businessgoals','ventures','skill','innovators','prototype','growthmindset','pitching','innovations','businesslife','businessstrategy','smallbusinessowners','financial','companies','entrepreneurlifestyle','franchise','manufactures','beyourownboss']

In [86]:
sma_vec = vect.fit(smartcity)
sc100_features['sma_bow'] = sc100_features['tweets_merged'].apply(lambda x: np.sum(sma_vec.transform([x]).toarray()))

In [87]:
civ_vec = vect.fit(civictech)
sc100_features['civ_bow'] = sc100_features['tweets_merged'].apply(lambda x: np.sum(civ_vec.transform([x]).toarray()))

In [88]:
inf_vec = vect.fit(infrastructure)
sc100_features['inf_bow'] = sc100_features['tweets_merged'].apply(lambda x: np.sum(inf_vec.transform([x]).toarray()))

In [89]:
sus_vec = vect.fit(sustainability)
sc100_features['sus_bow'] = sc100_features['tweets_merged'].apply(lambda x: np.sum(sus_vec.transform([x]).toarray()))

In [90]:
gov_vec = vect.fit(governance)
sc100_features['gov_bow'] = sc100_features['tweets_merged'].apply(lambda x: np.sum(gov_vec.transform([x]).toarray()))

In [91]:
ent_vec = vect.fit(entrepreneurship)
sc100_features['ent_bow'] = sc100_features['tweets_merged'].apply(lambda x: np.sum(ent_vec.transform([x]).toarray()))

#### Are there differences of performance to weighting BoWs between tweets_merged and clean_text ?

In [94]:
sc100_features['sma_tok'] = sc100_features['clean_text'].apply(lambda x: np.sum(sma_vec.transform([x]).toarray()))

In [95]:
sc100_features['civ_tok'] = sc100_features['clean_text'].apply(lambda x: np.sum(civ_vec.transform([x]).toarray()))

In [96]:
sc100_features['inf_tok'] = sc100_features['clean_text'].apply(lambda x: np.sum(inf_vec.transform([x]).toarray()))

In [97]:
sc100_features['sus_tok'] = sc100_features['clean_text'].apply(lambda x: np.sum(sus_vec.transform([x]).toarray()))

In [98]:
sc100_features['gov_tok'] = sc100_features['clean_text'].apply(lambda x: np.sum(gov_vec.transform([x]).toarray()))

In [99]:
sc100_features['ent_tok'] = sc100_features['clean_text'].apply(lambda x: np.sum(ent_vec.transform([x]).toarray()))

In [100]:
sc100_features.head()

,city_id,rank2020,num_tweets,avg_tweet_len,avg_num_words,avg_stopwords,avg_num_sentences,avg_word_len,avg_punctuation,avg_hashtags,avg_numerics,avg_upper,avg_neg,avg_neu,avg_pos,avg_compound,tweets_merged,total_words,total_stopwords,total_punctuation,total_hashtags,total_numerics,total_upper,clean_text,total_clean_words,total_clean_char,avg_clean_word_len,tokens,most_freq100,sma_bow,civ_bow,inf_bow,sus_bow,gov_bow,ent_bow,sma_tok,civ_tok,inf_tok,sus_tok,gov_tok,ent_tok
0,abudhabi,42,832,193.930288,25.002404,5.794471,1.435096,7.076026,14.016827,4.602163,0.278846,1.091346,0.021933,0.860132,0.117936,0.299883,'A Delegation from @aau_ae visited @BurjeelMe...,166602,4811,15703,3268,202,760,delegation aau_ae visited burjeelmedicity one ...,14484,173030,11.2,"[delegation, aau_ae, visited, burjeelmedicity,...","[(abudhabi, 677), (uae, 224), (abu, 156), (dub...",313,290,345,258,312,328,335,335,335,335,335,335
1,abuja,107,828,209.646135,27.042271,5.580918,1.437198,7.075491,15.369565,5.787440,0.404589,1.263285,0.018193,0.856400,0.125396,0.356573,"'Brother #Abuja https://t.co/6J3yOIP8Jm', 'Our...",180295,4561,18553,3862,232,766,brother abuja httpsSkeptical_annoyed_undecided...,15083,182674,11.4,"[brother, abuja, httpsSkeptical_annoyed_undeci...","[(abuja, 635), (lagos, 163), (abujatwittercomm...",249,200,320,66,287,394,398,398,398,398,398,398
2,amsterdam,9,1000,180.311000,22.627000,5.220000,1.520000,7.579219,14.554000,5.239000,0.153000,0.663000,0.024567,0.875009,0.100439,0.250798,'Herfst in #Amsterdam 🍂🍃🍁 https://t.co/F0VKRmq...,185912,5200,18994,4740,134,563,herfst amsterdam fallen_leafleaf_fluttering_in...,15579,197584,11.9,"[herfst, amsterdam, fallen_leafleaf_fluttering...","[(amsterdam, 993), (netherlands, 80), (day, 64...",381,241,339,103,195,299,295,295,295,295,295,295
3,ankara,57,313,185.808307,22.984026,3.974441,1.306709,7.510589,14.747604,5.623003,0.338658,0.840256,0.039681,0.865914,0.094422,0.192013,'I had a great and very joyful flight today ✈️...,60230,1241,6328,1426,77,224,great joyful flight today airplane nto ankara ...,5302,66000,11.7,"[great, joyful, flight, today, airplane, nto, ...","[(ankara, 251), (turkey, 77), (turkish, 26), (...",49,74,68,21,108,106,104,104,104,104,104,104
4,athens,99,1000,186.752000,24.268000,5.405000,1.503000,7.170592,15.201000,5.442000,0.226000,0.865000,0.042164,0.865646,0.092190,0.176392,'Georgia GA #GARunoffs\n#Sparta #Athens #Ciara...,192839,5370,20229,4795,180,766,georgia ga garunoffsnsparta athens ciara lukes...,16782,204722,11.5,"[georgia, ga, garunoffsnsparta, athens, ciara,...","[(athens, 867), (greece, 322), (greek, 74), (a...",247,324,284,104,272,315,317,317,317,317,317,317

In [101]:
# Save new .csv file with lastly created columns
sc100_features.to_csv('sc100_feature1.csv', index=False)